#!/usr/bin/env python

# plugin to check how long since the last update was done
# shamelessly based on check_yum

__author__  = "Hamish Downer"
__title__   = "Nagios Plugin for checking days since last Apt upgrade on Debian/Ubuntu systems"
__version__ = "0.0.1"


# Standard Nagios return codes
OK       = 0
WARNING  = 1
CRITICAL = 2
UNKNOWN  = 3

import os
from datetime import date
import sys
import signal
from optparse import OptionParser

DEFAULT_TIMEOUT = 30
DEFAULT_WARNING = 60
DEFAULT_CRITICAL = 90

def end(status, message):
    """Exits the plugin with first arg as the return code and the second
    arg as the message to output"""
    
    check = "APT "
    if status == OK:
        print "%sOK: %s" % (check, message)
        sys.exit(OK)
    elif status == WARNING:
        print "%sWARNING: %s" % (check, message)
        sys.exit(WARNING)
    elif status == CRITICAL:
        print "%sCRITICAL: %s" % (check, message)
        sys.exit(CRITICAL)
    else:
        print "UNKNOWN: %s" % message
        sys.exit(UNKNOWN)


APT = "/usr/bin/apt-get"

def check_apt_usable():
    """Checks that the APT program and path are correct and usable - that
    the program exists and is executable, otherwise exits with error"""

    if not os.path.exists(APT):
        end(UNKNOWN, "%s cannot be found" % APT)
    elif not os.path.isfile(APT):
        end(UNKNOWN, "%s is not a file" % APT)
    elif not os.access(APT, os.X_OK):
        end(UNKNOWN, "%s is not executable" % APT)


class AptUpdateChecker(object):
    def __init__(self):
        """Initialize all object variables"""

        self.timeout            = DEFAULT_TIMEOUT
        self.verbosity          = 0

    def validate_all_variables(self):
        """Validates all object variables to make sure the 
        environment is sane"""

        if self.timeout == None:
            self.timeout = DEFAULT_TIMEOUT
        try:
            self.timeout = int(self.timeout)
        except ValueError:
            end(UNKNOWN, "Timeout must be an whole number, " \
                       + "representing the timeout in seconds")

        if self.timeout < 1 or self.timeout > 3600:
            end(UNKNOWN, "Timeout must be a number between 1 and 3600 seconds")

        if self.warning == None:
            self.warning = DEFAULT_WARNING
        try:
            self.warning = int(self.warning)
        except ValueError:
            end(UNKNOWN, "Warning must be an whole number, " \
                       + "representing the update time limit in days")
        if self.warning < 1 or self.warning > 3650:
            end(UNKNOWN, "Warning must be a number between 1 and 3650 days")

        if self.critical == None:
            self.critical = DEFAULT_CRITICAL
        try:
            self.critical = int(self.critical)
        except ValueError:
            end(UNKNOWN, "Critical must be an whole number, " \
                       + "representing the update time limit in days")
        if self.critical < 1 or self.critical > 3650:
            end(UNKNOWN, "Critical must be a number between 1 and 3650 days")

        if self.warning > self.critical:
            end(UNKNOWN, "Warning cannot be larger than critical")

        if self.exclude == None:
            self.exclude_list = []
        else:
            self.exclude_list = self.exclude.split(',')

        if self.verbosity == None:
            self.verbosity = 0
        try:
            self.verbosity = int(self.verbosity)
            if self.verbosity < 0:
                raise ValueError
        except ValueError:
            end(UNKNOWN, "Invalid verbosity type, must be positive numeric " \
                        + "integer")

    def set_timeout(self):
        """sets an alarm to time out the test"""

        if self.timeout == 1:
            self.vprint(3, "setting plugin timeout to %s second" \
                                                                % self.timeout)
        else:
            self.vprint(3, "setting plugin timeout to %s seconds"\
                                                                % self.timeout)

        signal.signal(signal.SIGALRM, self.sighandler)
        signal.alarm(self.timeout)


    def sighandler(self, discarded, discarded2):
        """Function to be called by signal.alarm to kill the plugin"""

        # Nop for these variables
        discarded = discarded2
        discarded2 = discarded

        end(CRITICAL, "Apt nagios plugin has self terminated after " \
                    + "exceeding the timeout (%s seconds)" % self.timeout)


    def vprint(self, threshold, message):
        """Prints a message if the first arg is numerically greater than the
        verbosity level"""
        if self.verbosity >= threshold:
            print "%s" % message

    def gziplines(self, fname):
        # from http://spyced.blogspot.com/2006/12/wow-gzip-module-kinda-sucks.html
        from subprocess import Popen, PIPE
        f = Popen(['zcat', fname], stdout=PIPE)
        return f.stdout

    def convert_to_past_date(self, date_str):
        year,month,day = date_str.split('-')
        return date(int(year), int(month), int(day))

    def find_last_updated_date(self, logfile):
        if not os.path.exists(logfile):
            self.vprint(1, 'log file %s does not exist' % logfile)
            return None
        if os.path.getsize(logfile) == 0:
            self.vprint(1, 'log file %s has zero length' % logfile)
            return None
        last_date = None
        if logfile.endswith('.gz'):
            f = self.gziplines(logfile)
        else:
            f = open(logfile)
        try:
            search_for = 'Upgrade'
            while True:
                line = f.next()
                if search_for == 'Upgrade':
                    if line.startswith('Upgrade:'):
                        search_for = 'End-Date'
                else:
                    # expecting a line like:
                    # End-Date: 2012-05-31  15:01:25
                    if line.startswith('End-Date:'):
                        last_date = line.split()[1]
                        search_for = 'Upgrade'
        except StopIteration:
            pass
        if last_date == None:
            self.vprint(1, 'no lines with "Updated:" found in %s' % logfile)
            return None
        # convert date string to actual date
        self.vprint(3, 'Date found is %s' % last_date)
        return self.convert_to_past_date(last_date)

    def calc_days_ago(self, date):
        datediff = date.today() - date
        return datediff.days

    def check_last_apt_update(self):
        check_apt_usable()
        self.vprint(3, "%s - Version %s\nAuthor: %s\n" \
            % (__title__, __version__, __author__))
        
        self.validate_all_variables()
        self.set_timeout()

        # search for Upgrade: in history.log, or if not found, in history.log.1.gz
        logdir = '/var/log/apt'
        apt_logs = sorted([f for f in os.listdir(logdir) if f.startswith('history.log')])
        last_update = None
        for logfile in apt_logs:
            last_update = self.find_last_updated_date(os.path.join(logdir, logfile))
            if last_update:
                break

        if last_update == None:
            # apt never run
            status = CRITICAL
            message = 'No apt log files found, apt probably never run'
        else:
            days_since_update = self.calc_days_ago(last_update)
            if days_since_update == 1:
                message = '1 day since last apt update'
            else:
                message = '%d days since last apt update' % days_since_update

            if days_since_update < self.warning:
                status = OK
            elif days_since_update < self.critical:
                status = WARNING
            else:
                status = CRITICAL
        return status, message
            


def main():
    """Parses command line options and calls the test function"""

    update_checker = AptUpdateChecker()
    parser = OptionParser()

    parser.add_option( "-w", 
                       "--warning", 
                       dest="warning",
                       help="Issue WARNING if the last update was more than "  \
                          + "this many days ago.")

    parser.add_option( "-c", 
                       "--critical", 
                       dest="critical",
                       help="Issue CRITICAL if the last update was more than " \
                          + "this many days ago.")

    parser.add_option( "-t",
                       "--timeout",
                       dest="timeout",
                       help="Sets a timeout in seconds after which the "  \
                           +"plugin will exit (defaults to %s seconds). " \
                                                      % DEFAULT_TIMEOUT)
    parser.add_option( "-x", 
                       "--exclude", 
                       dest="exclude",
                       help="List of packages to ignore updates of when " +
                            "checking for last update. (For when you have " +
                            "a small number of packages auto-update.)")

    parser.add_option( "-v", 
                       "--verbose", 
                       action="count", 
                       dest="verbosity",
                       help="Verbose mode. Can be used multiple times to "     \
                          + "increase output. Use -vvv for debugging output. " \
                          + "By default only one result line is printed as "   \
                          + "per Nagios standards")

    parser.add_option( "-V",
                       "--version",
                       action="store_true",
                       dest="version",
                       help="Print version number and exit")

    (options, args) = parser.parse_args()

    if args:
        parser.print_help()
        sys.exit(UNKNOWN)

    update_checker.warning      = options.warning
    update_checker.critical     = options.critical
    update_checker.exclude      = options.exclude
    update_checker.timeout      = options.timeout
    update_checker.verbosity    = options.verbosity

    if options.version:
        print "%s - Version %s\nAuthor: %s\n" \
            % (__title__, __version__, __author__)
        sys.exit(OK)
    
    result, output = update_checker.check_last_apt_update()
    end(result, output)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print "Caught Control-C..."
        sys.exit(CRITICAL)

# This plugin is based on the check_yum plugin available from
# https://code.google.com/p/check-yum/

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

